
name: Trigger Docusaurus Sync

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docusaurus repository sync
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/KumarRajan1/YOUR_DOCUSAURUS_REPO_NAME/dispatches \
            -d '{"event_type":"external-repo-updated","client_payload":{"repository":"docs1","ref":"${{ github.ref }}","sha":"${{ github.sha }}"}}'
